set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*RGB"

set -g default-shell /bin/zsh

set -g mouse on

set -g set-clipboard on

#ctrl+a instead of ctrl+b
unbind C-b 
set -g prefix C-a 
bind-key C-a send-prefix

# Change from 0 based to 1 based because keyboard layout
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# vim mode B) 
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

#reduce delay when pressing esc in vim
set -sg escape-time 10

bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U 
bind l select-pane -R 

# Split windows (opens in same directory)
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r 
bind r source-file ~/.config/tmux/tmux.conf 

#alt+hjkl to switch panes
bind -n M-h select-pane -L 
bind -n M-j select-pane -D 
bind -n M-k select-pane -U 
bind -n M-l select-pane -R

#alt+num to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

#colors
set -ogq @thm_accent "#f5d098"
set -ogq @thm_crust "#171c1f"
set -ogq @thm_mantle "#191e21"
set -ogq @thm_base "#1e2528"
set -ogq @thm_surface0 "#262f33"
set -ogq @thm_surface1 "#374145"
set -ogq @thm_surface2 "#4a585c"
set -ogq @thm_overlay0 "#58686d"
set -ogq @thm_overlay1 "#6f8788"
set -ogq @thm_overlay2 "#839e9a"
set -ogq @thm_subtext0 "#96b4aa"
set -ogq @thm_subtext1 "#adc9bc"
set -ogq @thm_text "#f8f9e8"
set -ogq @thm_red "#f57f82"
set -ogq @thm_orange "#f7a182"
set -ogq @thm_yellow "#f5d098"
set -ogq @thm_green "#cbe3b3"
set -ogq @thm_aqua "#b3e3ca"
set -ogq @thm_skye "#b3e6db"
set -ogq @thm_blue "#b2caed"
set -ogq @thm_purple "#d2bdf3"
set -ogq @thm_pink "#f3c0e5"

# messages
set -gF message-style "fg=#{@thm_crust},bg=#{@thm_accent},align=centre"
set -gF message-command-style "fg=#{@thm_text},bg=#{@thm_crust},align=centre"

# pane number indicator
set-option -gF display-panes-colour "#{@thm_accent}"
set-option -gF display-panes-active-colour "#{@thm_accent}"

# status line
set -gF status-style "bg=#{@thm_mantle},fg=#{@thm_text}"
set -gq @status_surface "#{@thm_surface0}"

# status left
set -gF status-left ""

# current_window
set -gq @_wc_left \
	"#[fg=#{@status_surface},bg=default]#{@window_left_separator}"
set -gq @_wc_right \
	"#[fg=#{@status_surface},bg=default]#{@window_right_separator}"
set -gq @_wc_number \
	"#[fg=#{@thm_accent},bg=#{@status_surface}]##I "
set -gq @_wc_text \
	"#[fg=#{@thm_subtext1},bg=#{@status_surface}] #{@current_command}"

set -gF window-status-current-format \
  "#[fg=default,bg=default]#{E:@_wc_left}#{E:@_wc_text} #{E:@_wc_number}#{E:@_wc_right}"

# inactive_window
set -gq @_w_left \
	"#[fg=#{@status_surface},bg=default]#{@window_left_separator}"
set -gq @_w_right \
	"#[fg=#{@status_surface},bg=default]#{@window_right_separator}"
set -gq @_w_number \
	"#[fg=#{@thm_accent},bg=#{@status_surface}]##I "
set -gq @_w_text \
	"#[fg=#{@thm_overlay1},bg=#{@status_surface}] #{@current_command}"

set -gF window-status-format \
  "#[fg=default,bg=default]#{E:@_w_left}#{E:@_w_text} #{E:@_w_number}#{E:@_w_right}"

# status right
set -gq @_s_left \
	"#[fg=#{@status_surface},bg=default]#{@window_left_separator}"
set -gq @_s_right \
	"#[fg=#{@status_surface},bg=default]#{@window_right_separator}"
set -gq @_s_text \
  "#[fg=#{@thm_text},bg=#{@status_surface}] #{b:pane_current_path} "

set -gF status-right "#{E:@_s_left}#{E:@_s_text}#{E:@_s_right}"

# vim: ft=tmux
