app-id=foot
title=Terminal

font=Tamzen:size=15:style=Regular
# geist mono nerd font:size=15:style=Regular
pad=8x8
dpi-aware=no

[colors-dark]
cursor=171c1f f5d098 
foreground=f8f9e8
background=000000
# 1e2528
regular0=374145
regular1=f57f82
regular2=cbe3b3
regular3=f5d098
regular4=b2caed
regular5=f3c0e5
regular6=b3e6db
regular7=adc9bc

bright0=4a585c
bright1=f57f82
bright2=cbe3b3
bright3=f5d098
bright4=b2caed
bright5=f3c0e5
bright6=b3e6db
bright7=96b4aa

16=f7a182
17=f6cee5

selection-foreground=f8f9e8
selection-background=374145

search-box-no-match=171c1f f57f82
search-box-match=f8f9e8 262f33

jump-labels=171c1f f7a182
urls=b2caed

alpha=1.0
